version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=defaultPasswordByGabriel123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  projectmanager:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    command: /bin/bash -c "dotnet ef database update --no-build --project /app/ProjectManager.csproj --startup-project /app/ProjectManager.csproj && dotnet ProjectManager.dll"


volumes:
  sql_data:
